# -*- coding: utf-8 -*-
"""Calculateur-d-IMC---Mini-projet-Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pun-HrW5Az6Wz0vwZJW3_cJYFx7iyRoQ
"""

# Variables
nom = "Rodriguez"
prenom = "Antoine"
age = 30
mois = 7
poids = 70
taille = 1.90
ville = "Toulon"
objectif = "Devenir Data Scientist"

# Fonction calcul IMC
def calcul_imc(poids, taille):
    return poids / (taille ** 2)

imc = calcul_imc(poids, taille)

# Statut IMC
if imc < 18.5:
    statut = "mince"
elif imc < 25:
    statut = "normal"
else:
    statut = "gros"

# Affichage final
print(f"En résumé, tu t’appelles {nom} {prenom}, tu as {age} ans et {mois} mois, "
      f"tu vis à {ville}, tu mesures {taille} m pour un poids de {poids} kg "
      f"avec un IMC de {imc:.2f}, ton statut est {statut} "
      f"et ton objectif est de devenir {objectif}.")